/**
 * The books: bank accounts, the chart of accounts, transactions, journal entries and the
 * financial reports. Served by the Accounting service rather than the portal API.
 */
import { z } from "zod";
import type { ToolDefinition } from "../registry.js";
import { oneOrMany, scope, selectPath } from "./shared.js";

/** Each report is a different endpoint under reports/. */
const REPORT_PATHS = {
  balanceSheet: "balance-sheet",
  incomeStatement: "income-statement",
  cashFlow: "cash-flow-statement",
  generalLedger: "general-ledger",
} as const;

const basis = z
  .enum(["Cash", "Accrual"])
  .describe("Cash counts money when it moves; Accrual counts it when it is earned or owed.");

const reportType = z
  .enum(["Property", "Company"])
  .describe("Property reports on the properties' own books; Company reports on the management company's.");

/** The dashboard serves each headline figure from its own endpoint. */
const SUMMARY_PATHS = {
  onTimeRent: "on-time-rent",
  onlinePayments: "online-payments",
  dailyMoneyMovement: "daily-money-movement",
  returnsAndDisputes: "returns-and-disputes",
} as const;

type SummaryName = keyof typeof SUMMARY_PATHS;

export const accountingTools: ToolDefinition[] = [
  // ---- The books ----------------------------------------------------------------------------

  {
    name: "get_bank_accounts",
    title: "Bank accounts",
    description:
      "The company's bank accounts with their balances and type. Pass bankAccountId for one in " +
      "full; omit it to list them. Use for 'how much is held where' questions.",
    service: "accounting",
    ...oneOrMany("bankAccountId", "bank-accounts"),
    schema: {
      bankAccountId: z.string().optional().describe("Return just this bank account, in full."),
      search: z.string().optional().describe("Free-text search on the account name."),
      active: z.boolean().optional().describe("Only active accounts when true."),
    },
  },
  {
    name: "get_chart_of_accounts",
    title: "Chart of accounts",
    description:
      "The ledger accounts the books are structured around, with their type and number. Pass " +
      "chartOfAccountId for one; omit it to list them. Use to find an account id before running a " +
      "general ledger.",
    service: "accounting",
    ...oneOrMany("chartOfAccountId", "chart-of-accounts"),
    schema: {
      chartOfAccountId: z.string().optional().describe("Return just this ledger account."),
      search: z.string().optional().describe("Free-text search on the account name or number."),
    },
  },
  {
    name: "get_bank_ledger_transfers",
    title: "Bank transfers",
    description:
      "Money moved between bank accounts, plus deposits and withdrawals recorded against them. " +
      "Pass bankLedgerTransferId for one in full; omit it to list them. Use for questions about " +
      "transfers rather than tenant payments.",
    service: "accounting",
    ...oneOrMany("bankLedgerTransferId", "bank-ledger-transfers"),
    schema: {
      bankLedgerTransferId: z.string().optional().describe("Return just this transfer, in full."),
      bankAccountId: z.string().optional().describe("Only transfers touching this bank account."),
    },
  },
  {
    name: "get_manual_journal_entries",
    title: "Manual journal entries",
    description:
      "Journal entries posted by hand rather than generated by the system. Pass " +
      "manualJournalEntryId for one with all its lines; omit it to list them. Use for questions " +
      "about adjustments and corrections someone made to the books.",
    service: "accounting",
    ...oneOrMany("manualJournalEntryId", "manual-journal-entries"),
    schema: {
      manualJournalEntryId: z.string().optional().describe("Return just this entry, with its lines."),
    },
  },

  {
    name: "get_transaction",
    title: "Get a transaction",
    description:
      "One accounting transaction in full — its lines, amounts, accounts and status. Use to drill " +
      "into a transaction id seen in a ledger or report.",
    service: "accounting",
    path: "transactions/{transactionId}",
    schema: { transactionId: z.string().describe("The transaction id, from a ledger or report.") },
  },
  {
    name: "list_deposit_slips",
    title: "List deposit slips",
    description:
      "Deposit slips grouping payments banked together. Use when reconciling a bank deposit " +
      "against the payments that make it up.",
    service: "accounting",
    path: "deposit-slips",
    paginated: true,
    schema: { bankAccountId: z.string().optional().describe("Only slips for this bank account.") },
  },

  // ---- Reports ------------------------------------------------------------------------------

  {
    name: "get_financial_report",
    title: "Get a financial report",
    description:
      "One of MagicDoor's core financial reports. balanceSheet gives assets, liabilities and " +
      "equity as at asOfDate. incomeStatement gives income, expenses and profit between " +
      "startDate and endDate. cashFlow gives money in and out over that period, broken down by " +
      "groupBy. generalLedger gives every posting to every account over that period — narrow it " +
      "with coaIds or it will be very large.",
    service: "accounting",
    path: (args) => selectPath(REPORT_PATHS, args.report, (segment) => `reports/${segment}`),
    consumes: ["report"],
    schema: {
      report: z
        .enum(["balanceSheet", "incomeStatement", "cashFlow", "generalLedger"])
        .describe("Which report to run."),
      basis,
      reportType,
      startDate: z.string().optional().describe("First day to include, YYYY-MM-DD. Not used by balanceSheet."),
      endDate: z.string().optional().describe("Last day to include, YYYY-MM-DD. Not used by balanceSheet."),
      asOfDate: z.string().optional().describe("The date to report as at, YYYY-MM-DD. balanceSheet only."),
      groupBy: z
        .enum(["Total", "Property", "Year", "Quarter", "Month"])
        .optional()
        .describe("How to break the statement down. cashFlow only."),
      coaIds: z.array(z.string()).optional().describe("Only these ledger accounts. generalLedger only."),
      ...scope,
    },
  },

  {
    name: "get_rent_payments_report",
    title: "Get the rent payments report",
    description:
      "Rent payments over a period, with how they were paid and whether they cleared. Use for " +
      "'what rent came in' and 'how are tenants paying' questions.",
    service: "accounting",
    path: "reports/rent-payments",
    schema: {
      "DateRange.Start": z.string().describe("First day to include, YYYY-MM-DD."),
      "DateRange.End": z.string().describe("Last day to include, YYYY-MM-DD."),
      ...scope,
    },
  },
  {
    name: "get_owner_statement",
    title: "Get an owner statement",
    description:
      "What an owner earned and was charged over a period, and what is due to them. Use for " +
      "questions about owner payouts and statements.",
    service: "accounting",
    path: "reports/owner-statement",
    schema: {
      startDate: z.string().describe("First day to include, YYYY-MM-DD."),
      endDate: z.string().describe("Last day to include, YYYY-MM-DD."),
      withUnpaidBills: z.boolean().optional().describe("Include bills that have not been paid yet."),
      ...scope,
    },
  },

  // ---- Dashboard summaries ------------------------------------------------------------------

  {
    name: "get_accounting_summary",
    title: "Get an accounting headline figure",
    description:
      "A single headline figure the dashboard shows, without totalling ledgers: how much rent was " +
      "paid on time, how much is paid online rather than by cheque, money in and out per day, or " +
      "payments that bounced or were disputed.",
    service: "accounting",
    path: (args) => {
      const segment = SUMMARY_PATHS[args.summary as SummaryName];
      if (!segment) {
        throw new Error(`summary must be one of: ${Object.keys(SUMMARY_PATHS).join(", ")}.`);
      }

      return `dashboard/${segment}`;
    },
    consumes: ["summary"],
    schema: {
      summary: z
        .enum(["onTimeRent", "onlinePayments", "dailyMoneyMovement", "returnsAndDisputes"])
        .describe("Which headline figure to fetch."),
    },
  },

];
