/**
 * The books: bank accounts, the chart of accounts, transactions, journal entries and the
 * financial reports. Served by the Accounting service rather than the portal API.
 */
import { z } from "zod";
import type { ToolDefinition } from "../registry.js";

const scope = {
  propertyIds: z.array(z.string()).optional().describe("Limit to these properties. Omit for the whole company."),
  portfolioIds: z.array(z.string()).optional().describe("Limit to these portfolios. Omit for the whole company."),
};

const basis = z
  .enum(["Cash", "Accrual"])
  .describe("Cash counts money when it moves; Accrual counts it when it is earned or owed.");

const reportType = z
  .enum(["Property", "Company"])
  .describe("Property reports on the properties' own books; Company reports on the management company's.");

/** The dashboard serves each headline figure from its own endpoint. */
const SUMMARY_PATHS = {
  onTimeRent: "on-time-rent",
  onlinePayments: "online-payments",
  dailyMoneyMovement: "daily-money-movement",
  returnsAndDisputes: "returns-and-disputes",
} as const;

type SummaryName = keyof typeof SUMMARY_PATHS;

const startDate = z.string().describe("First day to include, YYYY-MM-DD.");
const endDate = z.string().describe("Last day to include, YYYY-MM-DD.");

export const accountingTools: ToolDefinition[] = [
  // ---- The books ----------------------------------------------------------------------------

  {
    name: "list_bank_accounts",
    title: "List bank accounts",
    description:
      "The company's bank accounts with their balances and type. Use to find a bank account id, " +
      "or to answer questions about how much is held where.",
    service: "accounting",
    path: "bank-accounts",
    paginated: true,
    schema: {
      search: z.string().optional().describe("Free-text search on the account name."),
      active: z.boolean().optional().describe("Only active accounts when true."),
    },
  },
  {
    name: "get_bank_account",
    title: "Get a bank account",
    description: "One bank account in full, including its balance and how it is configured.",
    service: "accounting",
    path: "bank-accounts/{bankAccountId}",
    schema: { bankAccountId: z.string().describe("The bank account id, from list_bank_accounts.") },
  },
  {
    name: "list_chart_of_accounts",
    title: "List the chart of accounts",
    description:
      "The chart of accounts — every ledger account with its type and number. Use to find an " +
      "account id before running a general ledger, or to explain how the books are structured.",
    service: "accounting",
    path: "chart-of-accounts",
    paginated: true,
    schema: {
      search: z.string().optional().describe("Free-text search on the account name or number."),
    },
  },
  {
    name: "get_chart_of_account",
    title: "Get a ledger account",
    description: "One account from the chart of accounts, with its type, number and parent.",
    service: "accounting",
    path: "chart-of-accounts/{chartOfAccountId}",
    schema: { chartOfAccountId: z.string().describe("The account id, from list_chart_of_accounts.") },
  },
  {
    name: "get_transaction",
    title: "Get a transaction",
    description:
      "One accounting transaction in full — its lines, amounts, accounts and status. Use to drill " +
      "into a transaction id seen in a ledger or report.",
    service: "accounting",
    path: "transactions/{transactionId}",
    schema: { transactionId: z.string().describe("The transaction id, from a ledger or report.") },
  },
  {
    name: "list_bank_ledger_transfers",
    title: "List bank transfers",
    description:
      "Money moved between bank accounts, plus deposits and withdrawals recorded against them. " +
      "Use for questions about transfers rather than tenant payments.",
    service: "accounting",
    path: "bank-ledger-transfers",
    paginated: true,
    schema: { bankAccountId: z.string().optional().describe("Only transfers touching this bank account.") },
  },
  {
    name: "get_bank_ledger_transfer",
    title: "Get a bank transfer",
    description: "One bank transfer in full, including both sides of the movement.",
    service: "accounting",
    path: "bank-ledger-transfers/{bankLedgerTransferId}",
    schema: { bankLedgerTransferId: z.string().describe("The transfer id, from list_bank_ledger_transfers.") },
  },
  {
    name: "list_manual_journal_entries",
    title: "List manual journal entries",
    description:
      "Journal entries posted by hand rather than generated by the system. Use for questions " +
      "about adjustments and corrections someone made to the books.",
    service: "accounting",
    path: "manual-journal-entries",
    paginated: true,
    schema: {},
  },
  {
    name: "get_manual_journal_entry",
    title: "Get a manual journal entry",
    description: "One manual journal entry with all of its debit and credit lines.",
    service: "accounting",
    path: "manual-journal-entries/{manualJournalEntryId}",
    schema: { manualJournalEntryId: z.string().describe("The entry id, from list_manual_journal_entries.") },
  },
  {
    name: "list_deposit_slips",
    title: "List deposit slips",
    description:
      "Deposit slips grouping payments banked together. Use when reconciling a bank deposit " +
      "against the payments that make it up.",
    service: "accounting",
    path: "deposit-slips",
    paginated: true,
    schema: { bankAccountId: z.string().optional().describe("Only slips for this bank account.") },
  },

  // ---- Reports ------------------------------------------------------------------------------

  {
    name: "get_balance_sheet",
    title: "Get the balance sheet",
    description:
      "Assets, liabilities and equity as at a date. Use for 'what are we worth' and 'what do we " +
      "hold' questions.",
    service: "accounting",
    path: "reports/balance-sheet",
    schema: {
      basis,
      reportType,
      asOfDate: z.string().optional().describe("The date to report as at, YYYY-MM-DD. Defaults to today."),
      ...scope,
    },
  },
  {
    name: "get_income_statement",
    title: "Get the income statement",
    description:
      "Income and expenses over a period, and the resulting profit. Use for 'how did we do' and " +
      "'what did we spend' questions.",
    service: "accounting",
    path: "reports/income-statement",
    schema: { basis, reportType, startDate, endDate, ...scope },
  },
  {
    name: "get_cash_flow_statement",
    title: "Get the cash flow statement",
    description:
      "Money in and out over a period, grouped as you choose. Use for questions about cash " +
      "movement rather than accounting profit.",
    service: "accounting",
    path: "reports/cash-flow-statement",
    schema: {
      reportType,
      groupBy: z
        .enum(["Total", "Property", "Year", "Quarter", "Month"])
        .describe("How to break the statement down."),
      startDate,
      endDate,
      ...scope,
    },
  },
  {
    name: "get_general_ledger",
    title: "Get the general ledger",
    description:
      "Every posting to every account over a period, with running balances. The most detailed " +
      "financial view — narrow it with coaIds and a date range or it will be very large.",
    service: "accounting",
    path: "reports/general-ledger",
    schema: {
      basis,
      reportType,
      startDate,
      endDate,
      coaIds: z.array(z.string()).optional().describe("Only these ledger accounts, from list_chart_of_accounts."),
      ...scope,
    },
  },
  {
    name: "get_rent_payments_report",
    title: "Get the rent payments report",
    description:
      "Rent payments over a period, with how they were paid and whether they cleared. Use for " +
      "'what rent came in' and 'how are tenants paying' questions.",
    service: "accounting",
    path: "reports/rent-payments",
    schema: {
      "DateRange.Start": z.string().describe("First day to include, YYYY-MM-DD."),
      "DateRange.End": z.string().describe("Last day to include, YYYY-MM-DD."),
      ...scope,
    },
  },
  {
    name: "get_owner_statement",
    title: "Get an owner statement",
    description:
      "What an owner earned and was charged over a period, and what is due to them. Use for " +
      "questions about owner payouts and statements.",
    service: "accounting",
    path: "reports/owner-statement",
    schema: {
      startDate,
      endDate,
      withUnpaidBills: z.boolean().optional().describe("Include bills that have not been paid yet."),
      ...scope,
    },
  },

  // ---- Dashboard summaries ------------------------------------------------------------------

  {
    name: "get_accounting_summary",
    title: "Get an accounting headline figure",
    description:
      "A single headline figure the dashboard shows, without totalling ledgers: how much rent was " +
      "paid on time, how much is paid online rather than by cheque, money in and out per day, or " +
      "payments that bounced or were disputed.",
    service: "accounting",
    path: (args) => {
      const segment = SUMMARY_PATHS[args.summary as SummaryName];
      if (!segment) {
        throw new Error(`summary must be one of: ${Object.keys(SUMMARY_PATHS).join(", ")}.`);
      }

      return `dashboard/${segment}`;
    },
    consumes: ["summary"],
    schema: {
      summary: z
        .enum(["onTimeRent", "onlinePayments", "dailyMoneyMovement", "returnsAndDisputes"])
        .describe("Which headline figure to fetch."),
    },
  },

];
